# Generated by Django 4.0 on 2023-07-10 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproject',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
