# Generated by Django 4.0 on 2023-07-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_group_leader',
            field=models.BooleanField(default=False, verbose_name='For group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_group_member',
            field=models.BooleanField(default=False, verbose_name='For group memebers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_personal',
            field=models.BooleanField(default=False, verbose_name='For personal use'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='PersonalUser',
        ),
    ]
