# Generated by Django 4.0 on 2023-07-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_choosegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.customuser'),
        ),
    ]
