# Generated by Django 4.0 on 2023-07-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_companymodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
