# Generated by Django 4.0 on 2023-07-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_companymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentications.companymodel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_group_leader',
            field=models.BooleanField(default=False, verbose_name='Group Leader'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_group_member',
            field=models.BooleanField(default=False, verbose_name='Group Member'),
        ),
    ]
